name: Release
on:
  push:
    tags: ['v*']
permissions:
  contents: write
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build WP plugin zip (plugin-only)
        run: |
          cd wp-plugin
          test -d perceptor || { echo "perceptor/ missing"; exit 1; }
          mkdir -p ../dist
          (cd perceptor && zip -r "../../dist/perceptor-${GITHUB_REF_NAME}.zip" . >/dev/null)
      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.zip
